// =============================================================================
// Data Types
// =============================================================================

/** Alert severity determines urgency and visual treatment */
export type AlertSeverity = 'critical' | 'warning' | 'info'

/** Alert lifecycle status */
export type AlertStatus = 'firing' | 'resolved' | 'silenced'

/** Component that generated the alert */
export type AlertSource = 'broker' | 'market-data' | 'risk' | 'strategy' | 'portfolio' | 'system'

/** Silence lifecycle status */
export type SilenceStatus = 'active' | 'expired' | 'pending'

/** An individual alert instance generated by a component */
export interface Alert {
  id: string
  fingerprint: string
  name: string
  summary: string
  description: string
  severity: AlertSeverity
  status: AlertStatus
  source: AlertSource
  labels: Record<string, string>
  startsAt: string
  endsAt: string | null
  acknowledgedAt: string | null
  acknowledgedBy: string | null
  silenceId: string | null
}

/** A silence temporarily mutes alerts matching specific label criteria */
export interface Silence {
  id: string
  matchers: Array<{ label: string; value: string; isRegex: boolean }>
  createdBy: string
  comment: string
  startsAt: string
  endsAt: string
  status: SilenceStatus
  matchedAlertCount: number
}

/** A route defines how alerts are delivered based on label matchers */
export interface Route {
  id: string
  name: string
  matchers: Array<{ label: string; value: string }>
  receiver: string
  groupBy: string[]
  groupWait: string
  groupInterval: string
  repeatInterval: string
  enabled: boolean
  lastDeliveredAt: string | null
}

/** An inhibition rule suppresses target alerts when source alerts fire */
export interface InhibitionRule {
  id: string
  name: string
  description: string
  sourceMatch: Record<string, string>
  targetMatch: Record<string, string>
  equal: string[]
  enabled: boolean
  suppressedCount: number
}

/** Summary statistics for the alert system */
export interface AlertStats {
  firingCount: number
  criticalCount: number
  warningCount: number
  infoCount: number
  silencedCount: number
  resolvedLast24h: number
  activeSilenceCount: number
  activeInhibitionCount: number
}

// =============================================================================
// Component Props
// =============================================================================

export interface AlertsDashboardProps {
  /** Summary statistics for the alert system */
  alertStats: AlertStats
  /** Currently active (firing + silenced) alerts */
  alerts: Alert[]
  /** Alerts resolved in the last 24 hours */
  recentlyResolved: Alert[]
  /** Active and pending silences */
  silences: Silence[]
  /** Configured alert routing rules */
  routes: Route[]
  /** Configured inhibition rules */
  inhibitionRules: InhibitionRule[]
  /** Called when user acknowledges an alert */
  onAcknowledgeAlert?: (alertId: string) => void
  /** Called when user wants to silence an alert */
  onSilenceAlert?: (alertId: string) => void
  /** Called when user clicks an alert to view full detail */
  onViewAlertDetail?: (alertId: string) => void
  /** Called when user wants to create a new silence */
  onCreateSilence?: () => void
  /** Called when user expires a silence early */
  onExpireSilence?: (silenceId: string) => void
  /** Called when user edits a silence */
  onEditSilence?: (silenceId: string) => void
  /** Called when user toggles a route on/off */
  onToggleRoute?: (routeId: string, enabled: boolean) => void
  /** Called when user edits a route */
  onEditRoute?: (routeId: string) => void
  /** Called when user creates a new route */
  onCreateRoute?: () => void
  /** Called when user toggles an inhibition rule on/off */
  onToggleInhibition?: (ruleId: string, enabled: boolean) => void
  /** Called when user edits an inhibition rule */
  onEditInhibition?: (ruleId: string) => void
  /** Called when user creates a new inhibition rule */
  onCreateInhibition?: () => void
}
